### ISSUE TITLE
Throttle control going nuts

### ISSUE THREAD

**Issue by kumpuu** [InfernoSuperNova/forts-wheels-mod#12]
There are two issues I noticed:
- Often, throttle gets reset to a previous value when you deselect the engine
- Sometimes when you don't have any engine selected and do nothing it randomly starts driving

I can't reproduce this in sandbox mode right now, so I believe it only happens in coop. Fortships had similar issues with the altitude controller in coop...

**Comment by InfernoSuperNova** [comment]
The throttle resetting should be fixed, not sure why that'd be back.
For the random driving - are you the host? There's a big with the Forts networking that causes the slider to pop up for everyone when the host selects an engine. The fortships controller uses the same function to determine what device you have selected, hence why it shares this issue.

**Comment by kumpuu** [comment]
Yes i was indeed hosting, and both issues occured as host...
These are really super annoying - is there no workaround at all? if you want, I can try and contact the devs.

**Comment by InfernoSuperNova** [comment]
Fixed
