### ISSUE TITLE
Engine throttle resets when not selected

### ISSUE THREAD

**Issue by alexc96161** [InfernoSuperNova/forts-wheels-mod#2]

**Comment by SamsterBirdies** [comment]
happens only in tdm since nothing is stored in data.throttles for some spoopy reasons.

**Comment by InfernoSuperNova** [comment]
Which is extremely, extremely weird because data.throttles is the only place that throttle values are retrieved from

**Comment by SamsterBirdies** [comment]
perhaps the table gets cleared somehow later on in Update()

**Comment by SamsterBirdies** [comment]
im currently suspecting ClearOldStructures()
