### ISSUE TITLE
Major framerate drop when controlling a vehicle

### ISSUE THREAD

**Issue by LilRenn** [InfernoSuperNova/forts-wheels-mod#38]
On one of the maps I'm working on, controlling vehicles by selecting the engine causes major framerate drop. I'm not sure why this is, but it could be something to do with the fact that the wheels seem to have multiple sets of tracks attached to them? This only happens outside of the map editor, as the extra set of tracks and fps drop are both nonexistent there.

Also, it looks like you can't see the framerate going down in the video, but the portions where the video goes fast or stops completely are when it happens.

https://github.com/InfernoSuperNova/forts-wheels-mod/assets/134165959/0812e355-0dc9-43a3-ae0a-b4681d5ffe33

**Comment by InfernoSuperNova** [comment]
Can you please ensure you are on the latest version?

**Comment by LilRenn** [comment]
How do I guarantee that the mod is updated?
