### ISSUE TITLE
Move effects instead of creating/destroying them

### ISSUE THREAD

**Issue by alexc96161** [InfernoSuperNova/forts-wheels-mod#5]
This should improve performance and smoothness theoretically. (Using [SetEffectDirection](https://www.earthworkgames.com/content/docs/FortsAPI.html#SetEffectDirection) and
[SetEffectPosition](https://www.earthworkgames.com/content/docs/FortsAPI.html#SetEffectPosition))

**Comment by InfernoSuperNova** [comment]
Interpolate as well using OnDraw

**Comment by InfernoSuperNova** [comment]
Requires dev assistance unfortunately. Closing for now.
